services:
  ingest-news:
    build: .
    volumes:
      - .:/app
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/home/appuser/.config/gcloud/application_default_credentials.json
    command: python -m src.data_ingestion.collect_news

  preprocess-news:
    build: .
    volumes:
      - .:/app
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/home/appuser/.config/gcloud/application_default_credentials.json
    command: python -m src.preprocessing.preprocess_news

  airflow:
    build: .
    container_name: guardian-news-airflow
    volumes:
      - .:/app
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - AIRFLOW_HOME=/app/airflow_home
      - AIRFLOW__CORE__DAGS_FOLDER=/app/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    ports:
      - "8080:8080"
    command: airflow standalone